FROM node:16.13.1-buster-slim  as deps-intermediate
ENV NODE_ENV development
RUN mkdir -p /app &&  chown node:node /app 
WORKDIR /app
USER node
COPY package*.json .
RUN npm install

FROM node:16.13.1-buster-slim as final
RUN mkdir -p /app &&  chown node:node /app 
WORKDIR /app
RUN chown node:node /app
USER node
# COPY --chown=node:node  . .    
# COPY --chown=node:node  --from=deps-intermediate ./app/node_modules ./node_modules

CMD ["npm", "start" ]